In [105]:
import pandas
from pandas_datareader import data
from datetime import datetime
from bokeh.plotting import figure, show, output_file

start = datetime(2016,12,1)
end = datetime(2017,3,17)
df = data.DataReader(name="SQ",data_source="yahoo",start=start,end=end)


def inc_dec(c, o):
    if c > o:
        value="Increase"
    elif c < o:
        value="Decrease"
    else:
        value="Equal"
    return value

df["Status"] = [inc_dec(c,o) for c,o in zip(df.Close,df.Open)]

df["Middle"] = (df.Close+df.Open)/2
df["Height"] = abs(df.Close-df.Open)

p=figure(x_axis_type="datetime",width=1000,height=300,responsive=True)
p.title.text="Candlestick Chart"
p.grid.grid_line_alpha=0.5

hours_12=12*60*60*1000
p.segment(df.index, df.High, df.index,df.Low,color="black")
p.rect(df.index[df.Status == "Increase"],df.Middle[df.Status == "Increase"],hours_12,df.Height[df.Status == "Increase"],fill_color="#CCFFFF",line_color="black")
p.rect(df.index[df.Status == "Decrease"],df.Middle[df.Status == "Decrease"],hours_12,df.Height[df.Status == "Decrease"],fill_color="#FF3333",line_color="black")


output_file("test.html")
show(p)

INFO:bokeh.core.state:Session output file 'test.html' already exists, will be overwritten.
ERROR:d:\program files (x86)\python35-32\lib\site-packages\bokeh\core\validation\check.py:E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name: #CCFFF [renderer: GlyphRenderer(id='641a777f-edf2-4a60-b63c-d9bb7dff38b7', ...)]

In [90]:
df

,Open,High,Low,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2017-03-01,17.530001,17.639999,17.059999,17.219999,13008800,17.219999,Decrease,17.375000,0.310002
2017-03-02,17.200001,17.350000,16.980000,16.990000,7289900,16.990000,Decrease,17.095000,0.210001
2017-03-03,16.830000,17.200001,16.570000,16.889999,13019700,16.889999,Increase,16.860000,0.059999
2017-03-06,16.910000,17.155001,16.709999,16.860001,6002000,16.860001,Decrease,16.885001,0.049999
2017-03-07,16.900000,16.900000,16.500000,16.760000,5490700,16.760000,Decrease,16.830000,0.140000
2017-03-08,16.760000,17.000000,16.700001,16.830000,3609100,16.830000,Increase,16.795000,0.070000
2017-03-09,16.850000,17.205000,16.700001,17.070000,5684100,17.070000,Increase,16.960000,0.220000
2017-03-10,17.139999,17.180000,16.830000,16.910000,4836800,16.910000,Decrease,17.024999,0.229999
2017-03-13,16.910000,17.091999,16.830000,16.930000,3714500,16.930000,Increase,16.920000,0.020000
2017-03-14,16.950001,16.950001,16.639999,16.770000,3734400,16.770000,Decrease,16.860000,0.180001
2017-03-15,16.799999,17.000000,16.740000,16.950001,4371600,16.950001,Increase,16.875000,0.150002
2017-03-16,17.000000,17.280001,17.000000,17.209999,8685800,17.209999,Increase,17.104999,0.209999
2017-03-17,17.180000,17.340000,17.059999,17.280001,5680700,17.280001,Increase,17.230001,0.100001